import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import  { Navbar }  from './Navbar'
import Footer from '@/components/footer/page'  // Adjust the path based on your project structure


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My-Portfolio',
  description: 'Generated by Q-Datasoft',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar pageName={''}/>
            {children}
        <Footer />
      </body>
    </html>
  )
}

